### ISSUE TITLE
COA object without accompanying CRS

### ISSUE THREAD

**Issue by jdpye** [RossDwyer/VTrack#15]
Ran into an issue at a workshop with a user building a COAData object fine, but it not having a CRS associated with it when it came time to build HRsummary + KUD estimates. The error message implied that there was a NA CRS value, but we thought it was misreading the user-provided one, and only realized later it was referring to the COAData attribute.

Setting that attribute manually using attr(COAData, "CRS")<- CRS('init=epsg:4326') worked as a solution, but not sure why that attribute was undefined on creation.

 Anyone else have this issue?

**Comment by jdpye** [comment]
Ah, seeing it's solved by:
https://gitlab.oceantrack.org/GreatLakes/glatos/merge_requests/22

I'll light a fire to get that merged, I guess!

Thanks!

**Comment by RossDwyer** [comment]
Thanks Jon, will get into this today.

Great to see the OTN workshop was such a resounding success!

On 28 Feb 2020, at 04:10, Jon Pye <notifications@github.com> wrote:

﻿

Ah, seeing it's solved by:
https://gitlab.oceantrack.org/GreatLakes/glatos/merge_requests/22

I'll light a fire to get that merged, I guess!

Thanks!
