### ISSUE TITLE
issues installing update VTrack

### ISSUE THREAD

**Issue by mauritsvzb** [RossDwyer/VTrack#21]
I'm experiencing issues when trying to update the VTrack package. The underlying issue seems to be the 'spdep' package. 

> devtools::install_github("rossdwyer/VTrack")
Downloading GitHub repo rossdwyer/VTrack@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                          
2: CRAN packages only           
3: None                         
4: spdep (1.2-2 -> 1.2-3) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 
Error: Failed to install 'VTrack' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/withr/R/withr.rdb' is corrupt
In addition: Warning messages:
1: In pkgbuild::build(pkgdir, dest_path = dest_path, binary = FALSE,  :
  restarting interrupted promise evaluation
2: In pkgbuild::build(pkgdir, dest_path = dest_path, binary = FALSE,  :
  internal error -3 in R_decompress1

Note that it doesn't wait for me to choose an option, either 1-4.

When i run 'Install.packages("spdep") and select 'Yes', following error emerges:

> install.packages("spdep")

  There is a binary version available but the source version is later:
      binary source needs_compilation
spdep  1.2-2  1.2-3              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Yes
installing the source package ‘spdep’

trying URL 'https://cran.rstudio.com/src/contrib/spdep_1.2-3.tar.gz'
Content type 'application/x-gzip' length 4047140 bytes (3.9 MB)
==================================================
downloaded 3.9 MB

* installing *source* package ‘spdep’ ...
** package ‘spdep’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c card.c -o card.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c dfs_ncomp.c -o dfs_ncomp.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c dnn.c -o dnn.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c gabriel.c -o gabriel.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c gearyw.c -o gearyw.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c gsymtest.c -o gsymtest.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c init.c -o init.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c insiders.c -o insiders.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c jc.c -o jc.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c knn.c -o knn.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c lagw.c -o lagw.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c listw2sn.c -o listw2sn.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c nbdists.c -o nbdists.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c polypoly.c -o polypoly.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c relative.c -o relative.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c skater.c -o skater.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c symtest.c -o symtest.o
clang -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o spdep.so card.o dfs_ncomp.o dnn.o gabriel.o gearyw.o gsymtest.o init.o insiders.o jc.o knn.o lagw.o listw2sn.o nbdists.o polypoly.o relative.o skater.o symtest.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [spdep.so] Error 1
ERROR: compilation failed for package ‘spdep’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/spdep’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/spdep’
Warning in install.packages :
  installation of package ‘spdep’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/cb/gj9pv0x5429dvzrnbqk9rlw40000gn/T/Rtmp0tSh5p/downloaded_packages’

Any advice how to solve this is greatly appreciated.

Thanks,
Maurits

**Comment by mauritsvzb** [comment]
Ok it works now after updating R and RStudio, along with 40 packages that are used by VTRack.

**Comment by RossDwyer** [comment]
Thanks Maurits, great that this issue was fixed with updating R ad RStudio
